name: DiabloSMP
version: 1.0
main: com.diablo.smp.DiabloSMP
api-version: 1.21
commands:
  diablo:
    description: Main Admin Command
    permission: diablo.admin
  trust:
    description: Trust a player for trading
