name: DiabloSMP
version: '${project.version}'
main: com.diablo.smp.DiabloSMP
api-version: '1.20'
authors: [ FlameAI ]
description: Custom DiabloSMP core plugin providing abilities and security.

commands:
  diablo:
    description: DiabloSMP admin commands.
    permission: diablosmp.admin
    usage: /diablo <give>
  trust:
    description: Trust another player to prevent friendly fire.
    usage: /trust <add|remove|list> [player]
